version: "2.23.3-desktop.2"

services:
  nginx:
    container_name: nginx
    build: ./NGINX/.
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: ./MariaDB/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./WordPress
    image: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    restart: always

volumes:
    wordpress:
        # name: wordpress
        # driver: local
        # driver_opts:
        #         device: /Users/mohammedchaoui/Desktop/wordpress_vol
        #         type : 'none'
        #         o:  'bind'
    mariadb:
        # name: mariadb
        # driver: local
        # driver_opts:
        #         device: /Users/mohammedchaoui/Desktop/mariadb_vol
        #         type : 'none'
        #         o:  'bind'